
services:
  edutrackone.api:
    build:
      context: .
      dockerfile: 1-Presentation/EduTrackOne.API/Dockerfile
    volumes:
      - ./:/src
    ports:
      - "7045:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      SA_PASSWORD: "EduTrackOne2025!"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=EduTrackOneDb;User=sa;Password=EduTrackOne2025!;TrustServerCertificate=True;"
    depends_on:
      - sqlserver
